parameters:
  - name: environments 
    type: object
    default: ["appdev"] 
  - name: OUTPUT_FOLDER_PATH
    type: string
    displayName: Folder path to look for the snapshot folder 
    default: artifacts

trigger: none
  # branches:
  #   include:
  #     - main
  # paths:
  #   exclude:
  #   - scripts.v3/*

stages:
- ${{ each environment in parameters.environments }}: 
  - stage: "${{ environment }}_deploy"
    displayName: "Release developer portal config to ${{ environment }}"
    variables:
      - group: "apim-dev-portal-appdev" #apim-dev-portal-${{ environment }}"       
    jobs:
      - deployment: release_dev_portal
        displayName: Release Dev Portal
        pool:
          name: DevOps-AzurePipelines-Ubuntu2204
        # creates an environment if it doesn't exist
        environment: $(ADO_ENVIRONMENT)
        strategy:
          # default deployment strategy, more coming...
          runOnce:
            deploy:
               steps:
                 - template: ./release-with-env.yaml 
                   parameters:
                     ENVIRONMENT: "${{ environment }}"
                     OUTPUT_FOLDER_PATH: ${{ parameters.OUTPUT_FOLDER_PATH }}

